# -*- coding: utf-8 -*-
"""Copy of falling-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfnDXc6UUgfxm_aCeMODDpo3aTDWtfE_
"""

!pip install ultralytics --no-deps
import pandas as pd
import os
import cv2
import shutil
import glob
from pathlib import Path
import random
from sklearn.model_selection import train_test_split
from ultralytics import YOLO
import matplotlib.pyplot as plt
import seaborn as sns

import kagglehub

path = kagglehub.dataset_download("uttejkumarkandagatla/fall-detection-dataset")

print("Path to dataset files:", path)

train_images_dir = Path("/kaggle/input/fall-detection-dataset/fall_dataset/images")
image_files = [
    f for f in train_images_dir.rglob("*")
    if f.suffix.lower() in [".jpg", ".jpeg", ".png"]
]

sample_files = random.sample(image_files, min(9, len(image_files)))

fig, axes = plt.subplots(3, 3, figsize=(20, 12))
axes = axes.flatten()

for ax, img_path in zip(axes, sample_files):
    img = cv2.imread(str(img_path))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    ax.imshow(img)
    ax.axis("off")
    ax.set_title(img_path.name, fontsize=20)

plt.tight_layout()
plt.show()

import os
DATASET_PATH = "/kaggle/input/fall-detection-dataset/fall_dataset/images"

for root, dirs, files in os.walk(DATASET_PATH):
    print(root, "->", len(files), "files")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/dataset.yaml
# path: /kaggle/input/fall-detection-dataset/fall_dataset
# 
# train: images/train
# val: images/val
# 
# nc: 2
# 
# names:
#   0: fallen
#   1: not fallen

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

model.train(
    data="/content/dataset.yaml",
    epochs=50,
    imgsz=640,
    batch=32,
    device=0,        # GPU
    workers=4,
    optimizer="AdamW",
    lr0=0.001,
    patience=20,
    project="fall_detection",
    name="yolo11"
)

# !rm -rf /content/lying_standing_detection/yolo11

shutil.make_archive(
    "fall_model",
    'zip',
    "/content/fall_detection/yolo11/weights"
)

!find /content -name "*.png" -o -name "*.jpg" | head -20

from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
# Define the path to the directory containing the images
#image_directory = "/kaggle/working/runs/detect/train2"
image_directory ='/content/fall_detection/yolo11'

# Iterate through all image files in the directory
for filename in os.listdir(image_directory):
    if filename.lower().endswith((".jpg",".png")):
        image_path = os.path.join(image_directory, filename)
        image = Image.open(image_path)

        # Display the image
        plt.figure(figsize=(12, 12), dpi=150)
        plt.imshow(image)
        plt.title(f"Image: {filename}", fontsize=20, fontweight='bold', color='blue')  # Customize font properties
        plt.axis("off")  # Hide axes
        plt.show()



from google.colab import drive
drive.mount('/content/drive')